server:
  port: 8848
  servlet:
    context-path: /


# Datasource Config
web:
  uploadPath: D:/Media/pcinthis/

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: localhost
    port: 6379 # Redis 服务器连接端口
    password: # Redis 服务器连接密码（默认为空）
    timeout: 5000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
      shutdown-timeout: 0ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    static-path-pattern: /pic/**    # 配置静态资源路径
  web:
    resources:
      static-locations: file:${web.uploadPath}    #配置文件上传路径
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblogdb
    username: root
    password: 123456
    #初始化时建立物理连接的个数
    druid:
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #开启日志输出
    map-underscore-to-camel-case: true

#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: myblog-group
#    send-message-timeout: 3000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


